### ISSUE TITLE
PlatformException (native_push_error, null, java.lang.NullPointerException)

### ISSUE THREAD

**Issue by Spinaker70** [Native-Push/native_push#1] opened 2024-07-18 07:51 UTC
Hi

When I start the application I get the error:

```
PlatformException(native_push_error, null, java.lang.NullPointerException
      	at com.opdehipt.native_push.NativePushPlugin$initialize$2.invokeSuspend(NativePushPlugin.kt:228)
      	at com.opdehipt.native_push.NativePushPlugin$initialize$2.invoke(NativePushPlugin.kt:0)
      	at com.opdehipt.native_push.NativePushPlugin$initialize$2.invoke(NativePushPlugin.kt:0)
      	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
      	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
      	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
      	at com.opdehipt.native_push.NativePushPlugin.initialize(NativePushPlugin.kt:214)
      	at com.opdehipt.native_push.NativePushPlugin.access$initialize(NativePushPlugin.kt:37)
      	at com.opdehipt.native_push.NativePushPlugin$onMethodCall$1.invokeSuspend(NativePushPlugin.kt:127)
      	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
      	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
      	at android.os.Handler.handleCallback(Handler.java:873)
      	at android.os.Handler.dispatchMessage(Handler.java:99)
      	at android.os.Looper.loop(Looper.java:201)
      	at android.app.ActivityThread.main(ActivityThread.java:6810)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
      , null)
```
Please help me understand what's wrong.

**Comment by svenopdehipt** [comment] 2024-07-18 08:17
It seems like you haven’t added the FCM options in the code. Please take a look at https://github.com/Native-Push/native_push/tree/main?tab=readme-ov-file#initialize-the-plugin. You have to add the following code and replace the firebaseOptions with your own.
```dart
await NativePush.instance.initialize(
    firebaseOptions: {
      'apiKey': 'YOUR_API_KEY',
      'projectId': 'YOUR_PROJECT_ID',
      'messagingSenderId': 'YOUR_MESSAGING_SENDER_ID',
      'appId': 'YOUR_APP_ID',
    },
    useDefaultNotificationChannel: true,
  );
```

You can get the the fcm options with the following command (the necessary script is in the root of this repo):
```sh
cat google-services.json | ./extract_fcm_options.sh <android-bundle-id>
```
The android bundle id is your android application id which you specified at the project setup. The script currently only works under Linux and macOS and you need to have jq installed. If you need a Windows alternative, the please wait till I provide it later (or extract the information manually).

If you haven’t created a firebase project yet, please take a look at step 1 and 2 of option 1 on this site:
https://firebase.google.com/docs/android/setup?hl=en#console

Please also look at the platform specific setup guide in the README (https://github.com/Native-Push/native_push?tab=readme-ov-file#platform-specifics) and make sure you have initialized everything which is necessary for your platform.

**Comment by Spinaker70** [comment] 2024-07-18 08:24
Secret data changed...

```
 @override
  Future<void> init() async {
    const nativePushInstance = NativePush.instance;

    await nativePushInstance.initialize(firebaseOptions: {
      'apiKey': 'AIzaSyCefefwJZkLOe7gZjewfeweE8werfewfDYjM',
      'appId': '1:63702387482229:android:fdff75c12e53298275038cfc',
      'messagingSenderId': '637092835549',
      'projectId': 'uscs-neotelecom',
    });

    await nativePushInstance.registerForRemoteNotification(options: [NotificationOption.alert, NotificationOption.badge, NotificationOption.sound]);

    nativePushInstance.notificationStream.listen((notification) {
      log('--- Received notification ---');
      _handleNotification(notification);
    });

    // Получаем push-уведомление из Terminated
    final initialNotification = await nativePushInstance.initialNotification();

    if (initialNotification != null) {
      log('--- Initial notification ---');
      _handleNotification(initialNotification);
    }

    // Обновление токена
    nativePushInstance.notificationTokenStream.listen((tokenData) {
      final (notificationService, token) = tokenData;

      if (token != null) _tokenController.add(token);
    });
  }
```

**Comment by Spinaker70** [comment] 2024-07-18 08:41
> cat google-services.json | ./extract_fcm_options.sh <android-bundle-id>


```
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
{projectId: .project_info.project_id, applicationId: .client.[] | select(.client_info.android_client_info.package_name=="ru.neotelecom.uscs") | .client_info.mobilesdk_app_id, apiKey: .client.[] | select(.client_info.android_client_info.package_name=="ru.neotelecom.uscs") | .api_key.[0].current_key}                                                             
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
{projectId: .project_info.project_id, applicationId: .client.[] | select(.client_info.android_client_info.package_name=="ru.neotelecom.uscs") | .client_info.mobilesdk_app_id, apiKey: .client.[] | select(.client_info.android_client_info.package_name=="ru.neotelecom.uscs") | .api_key.[0].current_key}                                                                                                                                                                                               
jq: 2 compile errors
```
jq-1.6
Ubuntu 22.04.4 LTS

**Comment by svenopdehipt** [comment] 2024-07-18 10:12
I have fixed a bug in android and will release a new version now. I would like to know if the lib does work for you now. I do not have a access to a linux machine currently and can't reproduce the jq bug on macOS, but I will look into it later.

**Comment by Spinaker70** [comment] 2024-07-18 13:23
> I have fixed a bug in android and will release a new version now. I would like to know if the lib does work for you now. I do not have a access to a linux machine currently and can't reproduce the jq bug on macOS, but I will look into it later.

Thanks for the quick response. I'll try to test it as soon as possible.

**Comment by svenopdehipt** [comment] 2024-07-18 20:40
I have now fixed the extract script.

**Comment by Spinaker70** [comment] 2024-07-19 02:07
`PlatformException(native_push_error, null, java.lang.NullPointerException
      	at com.opdehipt.native_push.NativePushPlugin$initialize$2.invokeSuspend(NativePushPlugin.kt:232)
      	at com.opdehipt.native_push.NativePushPlugin$initialize$2.invoke(NativePushPlugin.kt:0)
      	at com.opdehipt.native_push.NativePushPlugin$initialize$2.invoke(NativePushPlugin.kt:0)
      	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
      	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
      	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
      	at com.opdehipt.native_push.NativePushPlugin.initialize(NativePushPlugin.kt:218)
      	at com.opdehipt.native_push.NativePushPlugin.access$initialize(NativePushPlugin.kt:39)
      	at com.opdehipt.native_push.NativePushPlugin$onMethodCall$1.invokeSuspend(NativePushPlugin.kt:131)
      	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
      	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
      	at android.os.Handler.handleCallback(Handler.java:873)
      	at android.os.Handler.dispatchMessage(Handler.java:99)
      	at android.os.Looper.loop(Looper.java:201)
      	at android.app.ActivityThread.main(ActivityThread.java:6810)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
      , null)`

**Comment by Spinaker70** [comment] 2024-07-19 03:01
In the documentation we see the following:

 firebaseOptions: {
       'appId': 'YOUR_APP_ID',

In the code the variable is called differently: appId -> applicationId

The messagingSenderId variable is not mentioned in the code at all.

After the fixes, the application launched.

Additional debugging information:
```
W/Bundle  ( 9057): Key enable-checked-mode expected String but value was a java.lang.Boolean.  The default value <null> was returned.
W/Bundle  ( 9057): Attempt to cast generated internal exception:
W/Bundle  ( 9057): java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
W/Bundle  ( 9057): 	at android.os.BaseBundle.getString(BaseBundle.java:1167)
W/Bundle  ( 9057): 	at com.opdehipt.native_push.NativePushPlugin$Companion.parseNotification(NativePushPlugin.kt:94)
W/Bundle  ( 9057): 	at com.opdehipt.native_push.NativePushPlugin$Companion.access$parseNotification(NativePushPlugin.kt:41)
W/Bundle  ( 9057): 	at com.opdehipt.native_push.NativePushPlugin.getInitialNotification(NativePushPlugin.kt:244)
W/Bundle  ( 9057): 	at com.opdehipt.native_push.NativePushPlugin.access$getInitialNotification(NativePushPlugin.kt:39)
W/Bundle  ( 9057): 	at com.opdehipt.native_push.NativePushPlugin$onMethodCall$1.invokeSuspend(NativePushPlugin.kt:134)
W/Bundle  ( 9057): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/Bundle  ( 9057): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
W/Bundle  ( 9057): 	at android.os.Handler.handleCallback(Handler.java:873)
W/Bundle  ( 9057): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/Bundle  ( 9057): 	at android.os.Looper.loop(Looper.java:201)
W/Bundle  ( 9057): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
W/Bundle  ( 9057): 	at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  ( 9057): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/Bundle  ( 9057): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by svenopdehipt** [comment] 2024-07-19 07:47
Ok, I have corrected the variable name in the README.

The warning which you provided at the top is normal behavior because I try to parse all custom fields in the notification to return them in flutter and have therefor pass all fields. I expect all custom fields to be strings but some google set fields aren‘t strings. Google sometimes changes the field names so I can‘t filter out all fields set by google, but this shouldn’t impact the application because its only a warning. I already do some filtering with this code here:
```kotlin
val filteredKeys = keys
          .filterNot { it.startsWith("google") || it.startsWith("gcm") || it in listOf("from", "collapse_key") }
```
Does the app run without throwing any error or crashing?

**Comment by Spinaker70** [comment] 2024-07-19 08:20
```
PlatformException(native_push_error, null, java.lang.IllegalStateException: FirebaseApp name [DEFAULT] already exists!
      	at com.google.android.gms.common.internal.Preconditions.checkState(com.google.android.gms:play-services-basement@@18.3.0:2)
      	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:291)
      	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
      	at com.google.firebase.FirebaseKt.initialize(Firebase.kt:52)
      	at com.opdehipt.native_push.NativePushPlugin$initialize$2.invokeSuspend(NativePushPlugin.kt:235)
      	at com.opdehipt.native_push.NativePushPlugin$initialize$2.invoke(NativePushPlugin.kt:0)
      	at com.opdehipt.native_push.NativePushPlugin$initialize$2.invoke(NativePushPlugin.kt:0)
      	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
      	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
      	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
      	at com.opdehipt.native_push.NativePushPlugin.initialize(NativePushPlugin.kt:218)
      	at com.opdehipt.native_push.NativePushPlugin.access$initialize(NativePushPlugin.kt:39)
      	at com.opdehipt.native_push.NativePushPlugin$onMethodCall$1.invokeSuspend(NativePushPlugin.kt:131)
      	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
      	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
      	at android.os.Handler.handleCallback(Handler.java:873)
      	at android.os.Handler.dispatchMessage(Handler.java:99)
      	at android.os.Looper.loop(Looper.java:201)
      	at android.app.ActivityThread.main(ActivityThread.java:6810)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
      , null)
```

if(FirebaseApp.getApps().isEmpty()) {
       FirebaseApp.initializeApp(options);
}

**Comment by svenopdehipt** [comment] 2024-07-19 08:38
Fix will be there 1.0.2 in about 10 minutes.

**Comment by svenopdehipt** [comment] 2024-07-19 08:44
Is live now

**Comment by Spinaker70** [comment] 2024-07-19 08:49
Thank you. Now it works fine. I will test further...

**Closed as completed** 2024-07-19 11:29 UTC
